/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.interfaces;

/**
 *
 * @author charles cua
 */
public class Grades extends javax.swing.JPanel {

    /**
     * Creates new form Grades
     */
    public Grades() {
        initComponents();
        subject1.setText("button1");
        subject1.addActionListener(e -> showTab("sub1Tab"));

        subject2.setText("button2");
        subject2.addActionListener(e -> showTab("sub2Tab"));

        subject3.setText("button3");
        subject3.addActionListener(e -> showTab("sub3Tab"));

        subject4.setText("button4");
        subject4.addActionListener(e -> showTab("sub4Tab"));

        subject5.setText("button5");
        subject5.addActionListener(e -> showTab("sub5Tab"));

        subject6.setText("button6");
        subject6.addActionListener(e -> showTab("sub6Tab"));

        subject7.setText("button7");
        subject7.addActionListener(e -> showTab("sub7Tab"));

        subject8.setText("button8");
        subject8.addActionListener(e -> showTab("sub8Tab"));

        subject9.setText("button9");
        subject9.addActionListener(e -> showTab("sub9Tab"));

        subject10.setText("button10");
        subject10.addActionListener(e -> showTab("sub10Tab"));
        
        showTab("mathTab");
    }
    private void showTab(String tabName) {
    ((java.awt.CardLayout)panel2.getLayout()).show(panel2, tabName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new main.component.Panel();
        subject1 = new main.component.Button();
        panel2 = new main.component.Panel();
        sub1Tab = new main.interfaces.GradeTab();
        sub2Tab = new main.interfaces.GradeTab();
        sub3Tab = new main.interfaces.GradeTab();
        sub4Tab = new main.interfaces.GradeTab();
        sub5Tab = new main.interfaces.GradeTab();
        sub6Tab = new main.interfaces.GradeTab();
        sub7Tab = new main.interfaces.GradeTab();
        sub8Tab = new main.interfaces.GradeTab();
        sub9Tab = new main.interfaces.GradeTab();
        sub10Tab = new main.interfaces.GradeTab();
        subject2 = new main.component.Button();
        subject3 = new main.component.Button();
        subject4 = new main.component.Button();
        subject5 = new main.component.Button();
        subject6 = new main.component.Button();
        subject7 = new main.component.Button();
        subject8 = new main.component.Button();
        subject9 = new main.component.Button();
        subject10 = new main.component.Button();

        panel1.setArc(0);
        panel1.setPanelBackground(new java.awt.Color(0, 0, 0));
        panel1.setPreferredSize(new java.awt.Dimension(981, 652));

        subject1.setText("button1");
        subject1.addActionListener(this::subject1ActionPerformed);

        panel2.setPanelBackground(new java.awt.Color(102, 102, 102));
        panel2.setLayout(new java.awt.CardLayout());
        panel2.add(sub1Tab, "card2");
        panel2.add(sub2Tab, "card3");
        panel2.add(sub3Tab, "card4");
        panel2.add(sub4Tab, "card5");
        panel2.add(sub5Tab, "card6");
        panel2.add(sub6Tab, "card7");
        panel2.add(sub7Tab, "card8");
        panel2.add(sub8Tab, "card9");
        panel2.add(sub9Tab, "card10");
        panel2.add(sub10Tab, "card11");

        subject2.setText("button2");
        subject2.addActionListener(this::subject2ActionPerformed);

        subject3.setText("button3");
        subject3.addActionListener(this::subject3ActionPerformed);

        subject4.setText("button4");
        subject4.addActionListener(this::subject4ActionPerformed);

        subject5.setText("button5");
        subject5.addActionListener(this::subject5ActionPerformed);

        subject6.setText("button6");
        subject6.addActionListener(this::subject6ActionPerformed);

        subject7.setText("button7");
        subject7.addActionListener(this::subject7ActionPerformed);

        subject8.setText("button8");
        subject8.addActionListener(this::subject8ActionPerformed);

        subject9.setText("button9");
        subject9.addActionListener(this::subject9ActionPerformed);

        subject10.setText("button10");
        subject10.addActionListener(this::subject10ActionPerformed);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subject10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subject5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(subject3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(subject9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subject10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub1Tab");
    }//GEN-LAST:event_subject1ActionPerformed

    private void subject9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject9ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub9Tab");
    }//GEN-LAST:event_subject9ActionPerformed

    private void subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject5ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub5Tab");
    }//GEN-LAST:event_subject5ActionPerformed

    private void subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub2Tab");
    }//GEN-LAST:event_subject2ActionPerformed

    private void subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub3Tab");
    }//GEN-LAST:event_subject3ActionPerformed

    private void subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject4ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub4Tab");
    }//GEN-LAST:event_subject4ActionPerformed

    private void subject6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject6ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub6Tab");
    }//GEN-LAST:event_subject6ActionPerformed

    private void subject7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject7ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub7Tab");
    }//GEN-LAST:event_subject7ActionPerformed

    private void subject8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject8ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub8Tab");
    }//GEN-LAST:event_subject8ActionPerformed

    private void subject10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject10ActionPerformed
((java.awt.CardLayout)panel2.getLayout()).show(panel2, "sub10Tab");
    }//GEN-LAST:event_subject10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.component.Panel panel1;
    private main.component.Panel panel2;
    private main.interfaces.GradeTab sub10Tab;
    private main.interfaces.GradeTab sub1Tab;
    private main.interfaces.GradeTab sub2Tab;
    private main.interfaces.GradeTab sub3Tab;
    private main.interfaces.GradeTab sub4Tab;
    private main.interfaces.GradeTab sub5Tab;
    private main.interfaces.GradeTab sub6Tab;
    private main.interfaces.GradeTab sub7Tab;
    private main.interfaces.GradeTab sub8Tab;
    private main.interfaces.GradeTab sub9Tab;
    private main.component.Button subject1;
    private main.component.Button subject10;
    private main.component.Button subject2;
    private main.component.Button subject3;
    private main.component.Button subject4;
    private main.component.Button subject5;
    private main.component.Button subject6;
    private main.component.Button subject7;
    private main.component.Button subject8;
    private main.component.Button subject9;
    // End of variables declaration//GEN-END:variables
}
