/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.component;

/**
 *
 * @author Cyrus Wilson
 */
public class calendarTask extends javax.swing.JPanel {

    /**
     * Creates new form calendarTask
     */
    public calendarTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendarTaskLabel = new javax.swing.JLabel();
        calendarTaskArea = new javax.swing.JTextField();

        calendarTaskLabel.setText("YOUR TASKS");

        calendarTaskArea.setText("jTextField1");
        calendarTaskArea.addActionListener(this::calendarTaskAreaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendarTaskArea)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(calendarTaskLabel)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendarTaskLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calendarTaskArea, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calendarTaskAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarTaskAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calendarTaskAreaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField calendarTaskArea;
    private javax.swing.JLabel calendarTaskLabel;
    // End of variables declaration//GEN-END:variables
}
