/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.component;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author Cyrus Wilson
 */
public class CalendarComponent extends javax.swing.JPanel {
    // Variables declaration
    private CalendarNav calendarNav;
    private CalendarPanel calendarPanel;
    
    /**
     * Creates new form CalendarComponent
     */
    public CalendarComponent() {
        initComponents();
        setupCustomComponents();
        connectComponents();
    }
    
    private void setupCustomComponents() {
        // Remove the auto-generated layout and components
        this.removeAll();
        
        // Set our own layout
        this.setLayout(new java.awt.BorderLayout());
        
        // Create and add our components
        calendarNav = new CalendarNav();
        calendarPanel = new CalendarPanel();
        
        this.add(calendarNav, java.awt.BorderLayout.NORTH);
        this.add(calendarPanel, java.awt.BorderLayout.CENTER);
        
        // Connect them
        connectComponents();
    }
    
    private void connectComponents() {
        // Check if calendarNav exists
        if (calendarNav == null) {
            System.err.println("ERROR: calendarNav is null in connectComponents()");
            return;
        }
        
        calendarNav.addMonthChangeListener(newMonth -> {
            if (calendarPanel != null) {
                calendarPanel.setMonth(newMonth);
            }
        });
        
        System.out.println("Calendar components connected successfully");
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
        // Test method
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Calendar Test");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(800, 600);
            frame.setLocationRelativeTo(null);
            
            CalendarComponent calendar = new CalendarComponent();
            frame.add(calendar);
            frame.setVisible(true);
        });
    }
}
